"""WAF / block-page detection (§3.7 WAF-adapt, detection half).

Two jobs:
  * fingerprint the WAF from headers/cookies/server and from block-page bodies;
  * recognise a block response so the classifier never reports it as a hit —
    crucial against keyword-blocking WAFs (e.g. F5 ASM rejecting any path with
    `.old`/`.env`/`temp`), which a random-sibling check can't catch because a
    random path doesn't trip the rule.

Block bodies carry a per-request id (F5 "support ID", Akamai "reference #"),
so detection is by stable signature substrings, not body hashing.
"""

from __future__ import annotations

# name -> body substrings (lowercased) that identify a block page.
_BODY = {
    "F5 BIG-IP ASM": ("the requested url was rejected", "your support id is"),
    "Imperva Incapsula": ("incapsula incident id", "powered by incapsula",
                          "_incapsula_resource"),
    "Cloudflare": ("attention required! | cloudflare", "cloudflare ray id",
                   "error 1020", "access denied | cloudflare"),
    "Akamai": ("akamaighost", "reference&#32;#", "access denied</title>"),
    # bare "mod_security" intentionally omitted — too generic, would drop a legit
    # page that merely mentions the term; real block pages carry the full phrase.
    "ModSecurity": ("this error was generated by mod_security", "not acceptable!"),
    "Sucuri": ("sucuri website firewall", "access denied - sucuri"),
    "Wordfence": ("generated by wordfence",),
    "AWS WAF": ("<title>403 - forbidden: access is denied.</title>",),
}

# name -> (header-name, substring) signatures (header value lowercased, '' = any).
_HEADERS = {
    "Cloudflare": [("cf-ray", ""), ("server", "cloudflare")],
    "Imperva Incapsula": [("x-iinfo", ""), ("x-cdn", "incapsula")],
    "Akamai": [("server", "akamaighost"), ("x-akamai-transformed", "")],
    "Sucuri": [("x-sucuri-id", ""), ("x-sucuri-cache", "")],
    "F5 BIG-IP ASM": [("server", "volt-adc"), ("x-wa-info", "")],
    "Barracuda": [("server", "barracuda")],
}

# name -> cookie-name substrings.
_COOKIES = {
    "F5 BIG-IP": ("bigipserver", "ts01", "f5_cspm"),
    "Imperva Incapsula": ("incap_ses", "visid_incap"),
    "Cloudflare": ("__cfduid", "__cf_bm", "cf_clearance"),
    "Citrix Netscaler": ("ns_af", "citrix_ns_id"),
}


def detect_block_body(body_head: bytes) -> str | None:
    """WAF name if the body looks like a block page, else None."""
    text = body_head.lower().decode("latin-1", "replace")
    for name, needles in _BODY.items():
        if any(n in text for n in needles):
            return name
    return None


def detect_from_headers(headers: dict, cookies: list[str]) -> str | None:
    for name, sigs in _HEADERS.items():
        for hname, sub in sigs:
            val = headers.get(hname)
            if val is not None and (sub == "" or sub in val.lower()):
                return name
    cookie_blob = " ".join(cookies).lower()
    for name, needles in _COOKIES.items():
        if any(n in cookie_blob for n in needles):
            return name
    return None


def detect(probe) -> str | None:
    """Best-effort WAF name from one probe (body first, then headers/cookies)."""
    if not getattr(probe, "ok", False):
        return None
    return (detect_block_body(probe.body_head)
            or detect_from_headers(probe.headers, probe.cookies))


def is_block(probe) -> bool:
    """True if this response is a WAF block page (body signature)."""
    return detect_block_body(probe.body_head) is not None
